### ISSUE TITLE
directories 3.0.0 pins cfg-if 0.1.9, which breaks any dependency tree that also contains time 2.*

### ISSUE THREAD

**Issue by str4d** [dirs-dev/directories-rs#63]
This is the same issue as https://github.com/Geal/nom/issues/1156 (caused by https://github.com/Alexhuszagh/rust-lexical/issues/38 which similarly pins `cfg-if 0.1.9`); see there for further details.

**Comment by soc** [comment]
Fixed in v3.0.1.
