### ISSUE TITLE
Feature Request: Force MacOS to behave like Linux

### ISSUE THREAD

**Issue by chaosteil** [dirs-dev/directories-rs#84]
I have a CLI app that uses the [xdg crate](https://docs.rs/xdg/latest/xdg/). The current behavior of the crate is that even on OSX it returns Linux-like paths for the ones I care about, namely ~/.config/myapp. Now the crate itself doesn't support Windows (and will straight up refuse to compile on unixlikes), so I was looking for alternatives and found this crate.

My current issue is that I'm looking for something that can kind of bridge the gap with minimal intervention in the CLI code itself by allowing the behavior of Linux on OSX while retaining the behavior for Windows.

I know this doesn't quite meet the philosophy of the crate, but it would make eventual migration much easier. Additionally I'm quite sincere about my dotfiles, and I _do_ like the simplicity of .config files even on OSX (easier to check into my dotfiles), and this would allow me to continue the behavior and have some parity between my terminal configs on my various machines.

Is forcing Linux behavior on OSX something that could be considered at all? I would be happy to implement it myself as well.

**Comment by soc** [comment]
Hi Dominykas,
see https://github.com/dirs-dev/directories-rs/issues/47#issuecomment-478337412 for my position on this.
Thanks!
