### ISSUE TITLE
Library has a dependency with stronger license requirements

### ISSUE THREAD

**Issue by tomaka** [dirs-dev/directories-rs#88]
The `directories` library itself has the MIT or Apache2 license. However, it depends on `dirs-sys`, which itself depends on the `option-ext` library. The `option-ext` library is under the MPL-2 license.

While the MPL-2 license isn't very restrictive, it creates additional legal nuisance [just for 20 lines of code](https://github.com/soc/option-ext/blob/main/src/impl.rs). Would you consider relicensing `option-ext` under MIT/Apache, and/or removing this dependency altogether?

**Comment by soc** [comment]
See https://github.com/dirs-dev/dirs-sys-rs/issues/21#issuecomment-1531528155.
