### ISSUE TITLE
Optionally use XDG directories on mac

### ISSUE THREAD

**Issue by adriangalilea** [dirs-dev/directories-rs#89]
Hello,

I do have some Linux systems and Mac systems on which I have [common dotfiles](https://github.com/adriangalilea/dotfiles-rpi), I do use XDG paths on both, since I hate the file organisation on Mac and want to unify regardless.

Many programs pick up on XDG path envs regardless of the OS, but I believe programs running this library would not. I'm using [this library](https://github.com/adrg/xdg) for instance, which bases all the OS's paths on the XDG envs, just resolves differently for every OS, that means that I can control the paths both on linux and on mac, I also built [this program](https://github.com/adriangalilea/xdg-dirs) to manage precisely the XDG  paths with ease both on Mac and Linux.

So I'm guessing there's no way for me to have control over the resulting paths on a program using this library on Mac, right?

I know this is an extreme niche, but figured I'd ask anyway.

**Comment by soc** [comment]
Hi @adriangalilea, please see https://github.com/dirs-dev/directories-rs/issues/47#issuecomment-478337412.
